---
title: "Examples"
author: "Renato Panaro"
date: "July 3, 2019"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Laryngeal Cancer Data {.tabset .tabset-fade .tabset-pills}

```{r cars}

rm(list = ls()) # clear environment
set.seed(1) # reproducibility 

library(KMsurv) # database
  data("larynx")

## preprocessing data
larynx$status <- larynx$delta
larynx$age <- scale(larynx$age, scale = F)
```

##  Maximum Likelihood Estimation

### survival::coxph
```{r}
######## MAXIMUM LIKELIHOOD ESTIMATION (MLE) ########

 library('survival')
 coxphfit <- survival::coxph(Surv(time, status) ~ age + factor(stage),
            data = larynx)
 summary(coxphfit)
```

### spsurv::spbp 
```{r}
 library('spsurv')
 spbpfit <- spsurv::spbp(Surv(time, status) ~ age + factor(stage),
               data = larynx, approach = "mle")
 summary(spbpfit)
 
 plot(coxphfit$linear.predictors, bty = "n", ylab = "linear predictors(Z*beta)", xlab = "", cex = 1.5, cex.axis = 1.5)
 points(spbpfit$linear.predictors, pch = 19, cex = 1.5)
``` 

### stats::optim
```{r} 
 ## data prep
 Z <- matrix(model.matrix(coxphfit), nrow = dim(larynx)[1]); 
 colnames(Z) <- names(coxphfit$coefficients)
 Z <-  scale(Z, scale = F)
 n <- nrow(Z)
 q <- ncol(Z)
 m <- ceiling(sqrt(n)); cat("m = ", m)
 ## m =  10
 tau <- max(larynx$time); cat("tau = ", tau)
 ## tau =  10.7
 status = larynx$status
 if(is.null(status)){status = dat$status}
  
 # Polynomial basis  
 k <- 1:m
 b <- matrix(NA, n, m )
 B <- matrix(NA, n, m )
 y <- larynx$time/tau
 
  for (i in 1:n){
    for(k in 1:m){
      b[i,k] <- dbeta(y[i], k, m - k + 1) / tau
      B[i,k] <- pbeta(y[i], k, m - k + 1)
    }
  }
  
  loglik <- function(par, ## variables
                     m, status, Z, b, B){ ## data
    q <- length(par) - m
    gamma <- matrix(par[(q + 1):(q+m)], ncol = 1)
    gamma <- abs(gamma)
    beta <- matrix(par[1:q], ncol = 1)
    theta <- exp(Z %*% beta)
    
    h0 <-  b %*% gamma
    H0 <-  B %*% gamma
    res <- sum(status * log(h0 * theta) - H0 * theta)
    return(res)
  }

bpphfit   <- optim(c(rep(0, q), rep(1, m)), fn = loglik, method = "BFGS", control = list(fnscale=-1), m = m,
                status = status, Z = Z, b = b, B = B, hessian = TRUE)  
bpphfit
```

##  Bayesian Estimation
### spsurv::spbp
```{r}
spbpfit <- spsurv::spbp(Surv(time, status) ~ age + factor(stage),
               data = larynx, approach = "bayes", chain = 2, iter = 2000, warmup = 1000)

print(spbpfit$summary)
rstan::traceplot(spbpfit$stanfit, pars = c("beta", "gamma"))
coda::densplot(spbpfit$samp)
```

### HI::arms
```{r}
# data prep
Z <- matrix(model.matrix(coxphfit), nrow = dim(larynx)[1])
colnames(Z) <- names(coxphfit$coefficients)
Z <-  scale(Z, scale = F)
n <- nrow(Z)
q <- ncol(Z)
m <- ceiling(sqrt(n)); cat("m = ", m)
tau <- max(larynx$time); cat("tau = ", tau)
status <-  larynx$status

## Conditionals
l_gammak <- function(pi_k, k, ## variables
                     par, m, status, Z, b, B){  ## data
     j <- m - q
    gammak <- -log(pi_k); res <- NULL

    f <- function(par) {
      loglik( par = par, m = m, Z = Z, status = status, b = b, B = B )  +
      + (a_gammak - 1) * log(par[k]) - b_gammak * par[k]
    }

    for ( i in 1:length(gammak)){
      par_aux <- par
      par_aux[k] <- gammak[i]
      res[i] <- f(par_aux)
    }
  return( res - log(pi_k))
}


l_betaj <- function(pi_j, j, ## variables
                    par, m, status, Z, b, B){ ## data
   
    betaj <- log(pi_j) - log(1 - pi_j); res <- NULL
    f <- function(par){
      loglik( par = par, m = m, Z = Z, status = status, b = b, B = B ) -
        ( 1 / 2 ) * (par[j] - m_beta[q]) ^ 2   * 1/S_beta[q, q]
    }
    for ( i in 1:length(betaj)){
      par_aux <- par
      par_aux[j] <- betaj[i]
      res[i] <- f(par_aux)
    }
  return(res - log(pi_j) - log(1 - pi_j))
}

# prior
a_gammak = .01
b_gammak = .01

a_gammak / b_gammak
## [1] 1
a_gammak / (b_gammak)^2
## [1] 100
m_beta <- rep(0, q)
S_beta <- diag(100, q, q)

## ARS within Gibbs sampling
t <- 1
it <- 2000

par_samp <- matrix(NA, it, m + q)
colnames(par_samp) <- c(paste0("beta", 1:q), paste0("gamma", 1:m))

par <- c(rep(0, q), rep(1, m))
start_time <- Sys.time()

while(t < it + 1){
  for(j in 1:q){
    samp <- HI::arms( .5, myldens = function(y) l_betaj(y, j = j,
                                                        par = par, m = m, Z = Z, b = b, B = B, status = status),
                      indFunc = function(x){(x > 0) * (x <1)}, n.sample = 1 )

    par_samp[t, j] <- log(samp) - log(1 - samp)
    par[j] <- par_samp[t, j]
  }
  for(k in (q+1):(q+m)){
    samp <- HI::arms(.5, myldens = function(y) l_gammak(y, k = k,
                                                        par = par,m = m, Z = Z, b = b, B = B, status = status),
                     indFunc = function(x){(x > 0) * (x < 1)}, n.sample = 1 )

    par_samp[t, k] <- -log(samp)
    par[k] <- par_samp[t, k]
  }
  # cat( "\f", "Iteration", t, " out of ", it,". Time spent ",  Sys.time() - start_time)

  t <- t + 1
}
par_samp <- coda::mcmc(par_samp[((it/2)+1):it,1:4])

coda::traceplot(par_samp, main = '', bty = 'n')
coda::densplot(par_samp, main = '', bty = 'n')
```