comment: false
ignore:
  - "src/"  # ignore folders and all its contents

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

