---
title: "An introduction to `spbp` function"
author: "Renato Panaro"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
    highlight: tango
bibliography: references.bib
vignette: >
  %\VignetteIndexEntry{An introduction to `spsurv` package}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

# Installation {-}

Install latest development version from GitHub.

```{r, eval = F}
load("../data/PAT.rda")

if(!requireNamespace("devtools")) install.packages("devtools")
devtools::install_github("rvpanarpo/spsurv", auth_token = GIT_PATH)
```

# Examples {.tabset .tabset-fade .tabset-pills -}

## Bernstein Polynomial based PH {-}
```{r, eval =F}
library(spsurv)
db <- sim_weibull(100)

fit_coxph <- survival::coxph(Surv(y,status)~ X1 + X2,  data = db)
summary(fit_coxph)

fit_bpph <- spsurv::spbp(Surv(y,status)~ X1 + X2,  approach = "mle", data = db)
summary(fit_bpph)

```


```{r, eval = F}
library(spsurv)
```
