// Generated by rstantools.  Do not edit by hand.

/*
    spsurv is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    spsurv is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with spsurv.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_spbp_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 126> locations_array__ =
  {" (found before start of program)",
  " (in 'spbp', line 70, column 2 to column 17)",
  " (in 'spbp', line 71, column 2 to column 27)",
  " (in 'spbp', line 74, column 2 to column 29)",
  " (in 'spbp', line 75, column 2 to column 24)",
  " (in 'spbp', line 76, column 2 to column 14)",
  " (in 'spbp', line 77, column 2 to column 18)",
  " (in 'spbp', line 104, column 2 to column 43)",
  " (in 'spbp', line 98, column 4 to column 38)",
  " (in 'spbp', line 99, column 4 to column 37)",
  " (in 'spbp', line 100, column 4 to column 51)",
  " (in 'spbp', line 96, column 9 to line 102, column 3)",
  " (in 'spbp', line 79, column 11 to column 12)",
  " (in 'spbp', line 79, column 13 to column 14)",
  " (in 'spbp', line 79, column 4 to column 18)",
  " (in 'spbp', line 80, column 11 to column 12)",
  " (in 'spbp', line 80, column 13 to column 14)",
  " (in 'spbp', line 80, column 4 to column 18)",
  " (in 'spbp', line 81, column 11 to column 12)",
  " (in 'spbp', line 81, column 4 to column 33)",
  " (in 'spbp', line 82, column 4 to column 42)",
  " (in 'spbp', line 83, column 4 to column 42)",
  " (in 'spbp', line 84, column 4 to column 33)",
  " (in 'spbp', line 85, column 11 to column 12)",
  " (in 'spbp', line 85, column 4 to column 81)",
  " (in 'spbp', line 87, column 6 to column 28)",
  " (in 'spbp', line 88, column 6 to column 28)",
  " (in 'spbp', line 86, column 19 to line 89, column 5)",
  " (in 'spbp', line 86, column 4 to line 89, column 5)",
  " (in 'spbp', line 90, column 4 to column 24)",
  " (in 'spbp', line 91, column 4 to column 16)",
  " (in 'spbp', line 93, column 4 to column 37)",
  " (in 'spbp', line 94, column 4 to column 51)",
  " (in 'spbp', line 78, column 14 to line 96, column 3)",
  " (in 'spbp', line 78, column 2 to line 102, column 3)",
  " (in 'spbp', line 107, column 2 to column 25)",
  " (in 'spbp', line 113, column 8 to column 86)",
  " (in 'spbp', line 111, column 8 to column 84)",
  " (in 'spbp', line 110, column 6 to line 113, column 86)",
  " (in 'spbp', line 109, column 19 to line 114, column 5)",
  " (in 'spbp', line 109, column 4 to line 114, column 5)",
  " (in 'spbp', line 120, column 8 to column 61)",
  " (in 'spbp', line 119, column 11 to line 121, column 7)",
  " (in 'spbp', line 118, column 8 to column 64)",
  " (in 'spbp', line 117, column 6 to line 121, column 7)",
  " (in 'spbp', line 116, column 19 to line 122, column 5)",
  " (in 'spbp', line 116, column 4 to line 122, column 5)",
  " (in 'spbp', line 108, column 21 to line 123, column 3)",
  " (in 'spbp', line 108, column 2 to line 123, column 3)",
  " (in 'spbp', line 42, column 2 to column 17)",
  " (in 'spbp', line 43, column 2 to column 17)",
  " (in 'spbp', line 44, column 2 to column 17)",
  " (in 'spbp', line 45, column 2 to column 32)",
  " (in 'spbp', line 46, column 2 to column 25)",
  " (in 'spbp', line 47, column 26 to column 27)",
  " (in 'spbp', line 47, column 2 to column 36)",
  " (in 'spbp', line 48, column 18 to column 19)",
  " (in 'spbp', line 48, column 2 to column 26)",
  " (in 'spbp', line 49, column 9 to column 10)",
  " (in 'spbp', line 49, column 11 to column 12)",
  " (in 'spbp', line 49, column 2 to column 16)",
  " (in 'spbp', line 50, column 9 to column 10)",
  " (in 'spbp', line 50, column 11 to column 12)",
  " (in 'spbp', line 50, column 2 to column 16)",
  " (in 'spbp', line 51, column 9 to column 10)",
  " (in 'spbp', line 51, column 11 to column 12)",
  " (in 'spbp', line 51, column 2 to column 16)",
  " (in 'spbp', line 52, column 9 to column 10)",
  " (in 'spbp', line 52, column 11 to column 12)",
  " (in 'spbp', line 52, column 2 to column 16)",
  " (in 'spbp', line 53, column 30 to column 31)",
  " (in 'spbp', line 53, column 2 to column 33)",
  " (in 'spbp', line 54, column 9 to column 10)",
  " (in 'spbp', line 54, column 2 to column 26)",
  " (in 'spbp', line 55, column 18 to column 19)",
  " (in 'spbp', line 55, column 2 to column 32)",
  " (in 'spbp', line 57, column 31 to column 32)",
  " (in 'spbp', line 57, column 2 to column 34)",
  " (in 'spbp', line 58, column 18 to column 19)",
  " (in 'spbp', line 58, column 2 to column 36)",
  " (in 'spbp', line 59, column 18 to column 19)",
  " (in 'spbp', line 59, column 2 to column 33)",
  " (in 'spbp', line 60, column 9 to column 10)",
  " (in 'spbp', line 60, column 2 to column 18)",
  " (in 'spbp', line 61, column 18 to column 19)",
  " (in 'spbp', line 61, column 2 to column 25)",
  " (in 'spbp', line 66, column 9 to column 10)",
  " (in 'spbp', line 66, column 2 to column 33)",
  " (in 'spbp', line 70, column 9 to column 10)",
  " (in 'spbp', line 71, column 18 to column 19)",
  " (in 'spbp', line 74, column 9 to column 10)",
  " (in 'spbp', line 76, column 9 to column 10)",
  " (in 'spbp', line 77, column 9 to column 10)",
  " (in 'spbp', line 104, column 9 to column 10)",
  " (in 'spbp', line 8, column 4 to column 23)",
  " (in 'spbp', line 9, column 11 to column 12)",
  " (in 'spbp', line 9, column 4 to column 32)",
  " (in 'spbp', line 10, column 11 to column 12)",
  " (in 'spbp', line 10, column 4 to column 16)",
  " (in 'spbp', line 17, column 6 to column 13)",
  " (in 'spbp', line 16, column 11 to line 18, column 5)",
  " (in 'spbp', line 15, column 6 to column 25)",
  " (in 'spbp', line 14, column 23 to line 16, column 5)",
  " (in 'spbp', line 14, column 11 to line 18, column 5)",
  " (in 'spbp', line 13, column 6 to column 32)",
  " (in 'spbp', line 12, column 16 to line 14, column 5)",
  " (in 'spbp', line 12, column 4 to line 18, column 5)",
  " (in 'spbp', line 19, column 4 to column 13)",
  " (in 'spbp', line 7, column 62 to line 20, column 3)",
  " (in 'spbp', line 24, column 4 to column 23)",
  " (in 'spbp', line 25, column 11 to column 12)",
  " (in 'spbp', line 25, column 4 to column 32)",
  " (in 'spbp', line 26, column 11 to column 12)",
  " (in 'spbp', line 26, column 4 to column 32)",
  " (in 'spbp', line 27, column 11 to column 12)",
  " (in 'spbp', line 27, column 4 to column 20)",
  " (in 'spbp', line 34, column 6 to column 30)",
  " (in 'spbp', line 33, column 11 to line 35, column 5)",
  " (in 'spbp', line 32, column 6 to column 28)",
  " (in 'spbp', line 31, column 23 to line 33, column 5)",
  " (in 'spbp', line 31, column 11 to line 35, column 5)",
  " (in 'spbp', line 30, column 6 to column 52)",
  " (in 'spbp', line 29, column 16 to line 31, column 5)",
  " (in 'spbp', line 29, column 4 to line 35, column 5)",
  " (in 'spbp', line 36, column 4 to column 17)",
  " (in 'spbp', line 23, column 91 to line 37, column 3)"};
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_eigen_matrix_dynamic<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>,
                stan::base_type_t<T1__>, stan::base_type_t<T2__>>,-1,1>
cumhaz(const T0__& Gbas_arg__, const T1__& gamma_arg__, const T2__&
       eta_arg__, const int& M, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__,
          stan::require_all_t<stan::is_eigen_matrix_dynamic<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>,
                stan::base_type_t<T1__>, stan::base_type_t<T2__>,
                stan::base_type_t<T3__>, stan::base_type_t<T4__>>,-1,1>
log_haz(const T0__& gbas_arg__, const T1__& Gbas_arg__, const T2__&
        gamma_arg__, const T3__& eta_arg__, const T4__& log_t_arg__,
        const int& M, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_eigen_matrix_dynamic<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>>*>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>,
                stan::base_type_t<T1__>, stan::base_type_t<T2__>>,-1,1>
cumhaz(const T0__& Gbas_arg__, const T1__& gamma_arg__, const T2__&
       eta_arg__, const int& M, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>,
                             stan::base_type_t<T1__>,
                             stan::base_type_t<T2__>>;
  int current_statement__ = 0;
  const auto& Gbas = stan::math::to_ref(Gbas_arg__);
  const auto& gamma = stan::math::to_ref(gamma_arg__);
  const auto& eta = stan::math::to_ref(eta_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int n = std::numeric_limits<int>::min();
    current_statement__ = 94;
    n = stan::math::rows(Gbas);
    current_statement__ = 95;
    stan::math::validate_non_negative_index("B0", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> B0 =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 96;
    stan::model::assign(B0, stan::math::multiply(Gbas, gamma),
      "assigning variable B0");
    current_statement__ = 97;
    stan::math::validate_non_negative_index("H", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> H =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 106;
    if (stan::math::logical_eq(M, 0)) {
      current_statement__ = 104;
      stan::model::assign(H,
        stan::math::log1p(stan::math::elt_multiply(B0, stan::math::exp(eta))),
        "assigning variable H");
    } else {
      current_statement__ = 103;
      if (stan::math::logical_eq(M, 1)) {
        current_statement__ = 101;
        stan::model::assign(H,
          stan::math::elt_multiply(B0, stan::math::exp(eta)),
          "assigning variable H");
      } else {
        current_statement__ = 99;
        stan::model::assign(H, B0, "assigning variable H");
      }
    }
    current_statement__ = 107;
    return H;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__,
          stan::require_all_t<stan::is_eigen_matrix_dynamic<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>>*>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>,
                stan::base_type_t<T1__>, stan::base_type_t<T2__>,
                stan::base_type_t<T3__>, stan::base_type_t<T4__>>,-1,1>
log_haz(const T0__& gbas_arg__, const T1__& Gbas_arg__, const T2__&
        gamma_arg__, const T3__& eta_arg__, const T4__& log_t_arg__,
        const int& M, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>,
                             stan::base_type_t<T1__>,
                             stan::base_type_t<T2__>,
                             stan::base_type_t<T3__>,
                             stan::base_type_t<T4__>>;
  int current_statement__ = 0;
  const auto& gbas = stan::math::to_ref(gbas_arg__);
  const auto& Gbas = stan::math::to_ref(Gbas_arg__);
  const auto& gamma = stan::math::to_ref(gamma_arg__);
  const auto& eta = stan::math::to_ref(eta_arg__);
  const auto& log_t = stan::math::to_ref(log_t_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int n = std::numeric_limits<int>::min();
    current_statement__ = 109;
    n = stan::math::rows(gbas);
    current_statement__ = 110;
    stan::math::validate_non_negative_index("b0", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> b0 =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 111;
    stan::model::assign(b0, stan::math::multiply(gbas, gamma),
      "assigning variable b0");
    current_statement__ = 112;
    stan::math::validate_non_negative_index("B0", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> B0 =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 113;
    stan::model::assign(B0, stan::math::multiply(Gbas, gamma),
      "assigning variable B0");
    current_statement__ = 114;
    stan::math::validate_non_negative_index("log_h", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> log_h =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 123;
    if (stan::math::logical_eq(M, 0)) {
      current_statement__ = 121;
      stan::model::assign(log_h,
        stan::math::subtract(stan::math::add(stan::math::log(b0), eta),
          stan::math::log1p(
            stan::math::elt_multiply(B0, stan::math::exp(eta)))),
        "assigning variable log_h");
    } else {
      current_statement__ = 120;
      if (stan::math::logical_eq(M, 1)) {
        current_statement__ = 118;
        stan::model::assign(log_h, stan::math::add(stan::math::log(b0), eta),
          "assigning variable log_h");
      } else {
        current_statement__ = 116;
        stan::model::assign(log_h,
          stan::math::subtract(stan::math::log(b0), log_t),
          "assigning variable log_h");
      }
    }
    current_statement__ = 124;
    return log_h;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_spbp final : public model_base_crtp<model_spbp> {
private:
  int n;
  int m;
  int p;
  int approach;
  int M;
  Eigen::Matrix<double,-1,1> status_data__;
  Eigen::Matrix<double,-1,1> time_data__;
  Eigen::Matrix<double,-1,-1> X_data__;
  Eigen::Matrix<double,-1,-1> g_data__;
  Eigen::Matrix<double,-1,-1> G_data__;
  Eigen::Matrix<double,-1,-1> P_data__;
  std::vector<int> priordist_beta;
  Eigen::Matrix<double,-1,1> location_beta_data__;
  Eigen::Matrix<double,-1,1> scale_beta_data__;
  std::vector<int> priordist_gamma;
  Eigen::Matrix<double,-1,1> location_gamma_data__;
  Eigen::Matrix<double,-1,1> scale_gamma_data__;
  Eigen::Matrix<double,-1,1> means_data__;
  Eigen::Matrix<double,-1,1> sdv_data__;
  Eigen::Matrix<double,-1,1> log_time_data__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> status{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> time{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> g{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> G{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> P{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> location_beta{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> scale_beta{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> location_gamma{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> scale_gamma{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> means{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> sdv{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> log_time{nullptr, 0};
public:
  ~model_spbp() {}
  model_spbp(stan::io::var_context& context__, unsigned int
             random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_spbp_namespace::model_spbp";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 49;
      context__.validate_dims("data initialization", "n", "int",
        std::vector<size_t>{});
      n = std::numeric_limits<int>::min();
      current_statement__ = 49;
      n = context__.vals_i("n")[(1 - 1)];
      current_statement__ = 49;
      stan::math::check_greater_or_equal(function__, "n", n, 1);
      current_statement__ = 50;
      context__.validate_dims("data initialization", "m", "int",
        std::vector<size_t>{});
      m = std::numeric_limits<int>::min();
      current_statement__ = 50;
      m = context__.vals_i("m")[(1 - 1)];
      current_statement__ = 50;
      stan::math::check_greater_or_equal(function__, "m", m, 1);
      current_statement__ = 51;
      context__.validate_dims("data initialization", "p", "int",
        std::vector<size_t>{});
      p = std::numeric_limits<int>::min();
      current_statement__ = 51;
      p = context__.vals_i("p")[(1 - 1)];
      current_statement__ = 51;
      stan::math::check_greater_or_equal(function__, "p", p, 1);
      current_statement__ = 52;
      context__.validate_dims("data initialization", "approach", "int",
        std::vector<size_t>{});
      approach = std::numeric_limits<int>::min();
      current_statement__ = 52;
      approach = context__.vals_i("approach")[(1 - 1)];
      current_statement__ = 52;
      stan::math::check_greater_or_equal(function__, "approach", approach, 0);
      current_statement__ = 52;
      stan::math::check_less_or_equal(function__, "approach", approach, 1);
      current_statement__ = 53;
      context__.validate_dims("data initialization", "M", "int",
        std::vector<size_t>{});
      M = std::numeric_limits<int>::min();
      current_statement__ = 53;
      M = context__.vals_i("M")[(1 - 1)];
      current_statement__ = 53;
      stan::math::check_greater_or_equal(function__, "M", M, 0);
      current_statement__ = 53;
      stan::math::check_less_or_equal(function__, "M", M, 2);
      current_statement__ = 54;
      stan::math::validate_non_negative_index("status", "n", n);
      current_statement__ = 55;
      context__.validate_dims("data initialization", "status", "double",
        std::vector<size_t>{static_cast<size_t>(n)});
      status_data__ = Eigen::Matrix<double,-1,1>::Constant(n,
                        std::numeric_limits<double>::quiet_NaN());
      new (&status)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(status_data__.data(), n);
      {
        std::vector<local_scalar_t__> status_flat__;
        current_statement__ = 55;
        status_flat__ = context__.vals_r("status");
        current_statement__ = 55;
        pos__ = 1;
        current_statement__ = 55;
        for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
          current_statement__ = 55;
          stan::model::assign(status, status_flat__[(pos__ - 1)],
            "assigning variable status", stan::model::index_uni(sym1__));
          current_statement__ = 55;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 55;
      stan::math::check_greater_or_equal(function__, "status", status, 0);
      current_statement__ = 55;
      stan::math::check_less_or_equal(function__, "status", status, 1);
      current_statement__ = 56;
      stan::math::validate_non_negative_index("time", "n", n);
      current_statement__ = 57;
      context__.validate_dims("data initialization", "time", "double",
        std::vector<size_t>{static_cast<size_t>(n)});
      time_data__ = Eigen::Matrix<double,-1,1>::Constant(n,
                      std::numeric_limits<double>::quiet_NaN());
      new (&time) Eigen::Map<Eigen::Matrix<double,-1,1>>(time_data__.data(),
        n);
      {
        std::vector<local_scalar_t__> time_flat__;
        current_statement__ = 57;
        time_flat__ = context__.vals_r("time");
        current_statement__ = 57;
        pos__ = 1;
        current_statement__ = 57;
        for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
          current_statement__ = 57;
          stan::model::assign(time, time_flat__[(pos__ - 1)],
            "assigning variable time", stan::model::index_uni(sym1__));
          current_statement__ = 57;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 57;
      stan::math::check_greater_or_equal(function__, "time", time, 0);
      current_statement__ = 58;
      stan::math::validate_non_negative_index("X", "n", n);
      current_statement__ = 59;
      stan::math::validate_non_negative_index("X", "p", p);
      current_statement__ = 60;
      context__.validate_dims("data initialization", "X", "double",
        std::vector<size_t>{static_cast<size_t>(n), static_cast<size_t>(p)});
      X_data__ = Eigen::Matrix<double,-1,-1>::Constant(n, p,
                   std::numeric_limits<double>::quiet_NaN());
      new (&X) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_data__.data(), n, p);
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 60;
        X_flat__ = context__.vals_r("X");
        current_statement__ = 60;
        pos__ = 1;
        current_statement__ = 60;
        for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
          current_statement__ = 60;
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            current_statement__ = 60;
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 60;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 61;
      stan::math::validate_non_negative_index("g", "n", n);
      current_statement__ = 62;
      stan::math::validate_non_negative_index("g", "m", m);
      current_statement__ = 63;
      context__.validate_dims("data initialization", "g", "double",
        std::vector<size_t>{static_cast<size_t>(n), static_cast<size_t>(m)});
      g_data__ = Eigen::Matrix<double,-1,-1>::Constant(n, m,
                   std::numeric_limits<double>::quiet_NaN());
      new (&g) Eigen::Map<Eigen::Matrix<double,-1,-1>>(g_data__.data(), n, m);
      {
        std::vector<local_scalar_t__> g_flat__;
        current_statement__ = 63;
        g_flat__ = context__.vals_r("g");
        current_statement__ = 63;
        pos__ = 1;
        current_statement__ = 63;
        for (int sym1__ = 1; sym1__ <= m; ++sym1__) {
          current_statement__ = 63;
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            current_statement__ = 63;
            stan::model::assign(g, g_flat__[(pos__ - 1)],
              "assigning variable g", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 63;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 64;
      stan::math::validate_non_negative_index("G", "n", n);
      current_statement__ = 65;
      stan::math::validate_non_negative_index("G", "m", m);
      current_statement__ = 66;
      context__.validate_dims("data initialization", "G", "double",
        std::vector<size_t>{static_cast<size_t>(n), static_cast<size_t>(m)});
      G_data__ = Eigen::Matrix<double,-1,-1>::Constant(n, m,
                   std::numeric_limits<double>::quiet_NaN());
      new (&G) Eigen::Map<Eigen::Matrix<double,-1,-1>>(G_data__.data(), n, m);
      {
        std::vector<local_scalar_t__> G_flat__;
        current_statement__ = 66;
        G_flat__ = context__.vals_r("G");
        current_statement__ = 66;
        pos__ = 1;
        current_statement__ = 66;
        for (int sym1__ = 1; sym1__ <= m; ++sym1__) {
          current_statement__ = 66;
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            current_statement__ = 66;
            stan::model::assign(G, G_flat__[(pos__ - 1)],
              "assigning variable G", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 66;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 67;
      stan::math::validate_non_negative_index("P", "m", m);
      current_statement__ = 68;
      stan::math::validate_non_negative_index("P", "m", m);
      current_statement__ = 69;
      context__.validate_dims("data initialization", "P", "double",
        std::vector<size_t>{static_cast<size_t>(m), static_cast<size_t>(m)});
      P_data__ = Eigen::Matrix<double,-1,-1>::Constant(m, m,
                   std::numeric_limits<double>::quiet_NaN());
      new (&P) Eigen::Map<Eigen::Matrix<double,-1,-1>>(P_data__.data(), m, m);
      {
        std::vector<local_scalar_t__> P_flat__;
        current_statement__ = 69;
        P_flat__ = context__.vals_r("P");
        current_statement__ = 69;
        pos__ = 1;
        current_statement__ = 69;
        for (int sym1__ = 1; sym1__ <= m; ++sym1__) {
          current_statement__ = 69;
          for (int sym2__ = 1; sym2__ <= m; ++sym2__) {
            current_statement__ = 69;
            stan::model::assign(P, P_flat__[(pos__ - 1)],
              "assigning variable P", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 69;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 70;
      stan::math::validate_non_negative_index("priordist_beta", "p", p);
      current_statement__ = 71;
      context__.validate_dims("data initialization", "priordist_beta", "int",
        std::vector<size_t>{static_cast<size_t>(p)});
      priordist_beta = std::vector<int>(p, std::numeric_limits<int>::min());
      current_statement__ = 71;
      priordist_beta = context__.vals_i("priordist_beta");
      current_statement__ = 71;
      stan::math::check_greater_or_equal(function__, "priordist_beta",
        priordist_beta, 0);
      current_statement__ = 72;
      stan::math::validate_non_negative_index("location_beta", "p", p);
      current_statement__ = 73;
      context__.validate_dims("data initialization", "location_beta",
        "double", std::vector<size_t>{static_cast<size_t>(p)});
      location_beta_data__ = Eigen::Matrix<double,-1,1>::Constant(p,
                               std::numeric_limits<double>::quiet_NaN());
      new (&location_beta)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(location_beta_data__.data(),
        p);
      {
        std::vector<local_scalar_t__> location_beta_flat__;
        current_statement__ = 73;
        location_beta_flat__ = context__.vals_r("location_beta");
        current_statement__ = 73;
        pos__ = 1;
        current_statement__ = 73;
        for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
          current_statement__ = 73;
          stan::model::assign(location_beta, location_beta_flat__[(pos__ -
            1)], "assigning variable location_beta",
            stan::model::index_uni(sym1__));
          current_statement__ = 73;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 74;
      stan::math::validate_non_negative_index("scale_beta", "p", p);
      current_statement__ = 75;
      context__.validate_dims("data initialization", "scale_beta", "double",
        std::vector<size_t>{static_cast<size_t>(p)});
      scale_beta_data__ = Eigen::Matrix<double,-1,1>::Constant(p,
                            std::numeric_limits<double>::quiet_NaN());
      new (&scale_beta)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(scale_beta_data__.data(), p);
      {
        std::vector<local_scalar_t__> scale_beta_flat__;
        current_statement__ = 75;
        scale_beta_flat__ = context__.vals_r("scale_beta");
        current_statement__ = 75;
        pos__ = 1;
        current_statement__ = 75;
        for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
          current_statement__ = 75;
          stan::model::assign(scale_beta, scale_beta_flat__[(pos__ - 1)],
            "assigning variable scale_beta", stan::model::index_uni(sym1__));
          current_statement__ = 75;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 75;
      stan::math::check_greater_or_equal(function__, "scale_beta",
        scale_beta, 0);
      current_statement__ = 76;
      stan::math::validate_non_negative_index("priordist_gamma", "m", m);
      current_statement__ = 77;
      context__.validate_dims("data initialization", "priordist_gamma",
        "int", std::vector<size_t>{static_cast<size_t>(m)});
      priordist_gamma = std::vector<int>(m, std::numeric_limits<int>::min());
      current_statement__ = 77;
      priordist_gamma = context__.vals_i("priordist_gamma");
      current_statement__ = 77;
      stan::math::check_greater_or_equal(function__, "priordist_gamma",
        priordist_gamma, 0);
      current_statement__ = 78;
      stan::math::validate_non_negative_index("location_gamma", "m", m);
      current_statement__ = 79;
      context__.validate_dims("data initialization", "location_gamma",
        "double", std::vector<size_t>{static_cast<size_t>(m)});
      location_gamma_data__ = Eigen::Matrix<double,-1,1>::Constant(m,
                                std::numeric_limits<double>::quiet_NaN());
      new (&location_gamma)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(location_gamma_data__.data(),
        m);
      {
        std::vector<local_scalar_t__> location_gamma_flat__;
        current_statement__ = 79;
        location_gamma_flat__ = context__.vals_r("location_gamma");
        current_statement__ = 79;
        pos__ = 1;
        current_statement__ = 79;
        for (int sym1__ = 1; sym1__ <= m; ++sym1__) {
          current_statement__ = 79;
          stan::model::assign(location_gamma, location_gamma_flat__[(pos__ -
            1)], "assigning variable location_gamma",
            stan::model::index_uni(sym1__));
          current_statement__ = 79;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 79;
      stan::math::check_greater_or_equal(function__, "location_gamma",
        location_gamma, 0);
      current_statement__ = 80;
      stan::math::validate_non_negative_index("scale_gamma", "m", m);
      current_statement__ = 81;
      context__.validate_dims("data initialization", "scale_gamma", "double",
        std::vector<size_t>{static_cast<size_t>(m)});
      scale_gamma_data__ = Eigen::Matrix<double,-1,1>::Constant(m,
                             std::numeric_limits<double>::quiet_NaN());
      new (&scale_gamma)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(scale_gamma_data__.data(), m);
      {
        std::vector<local_scalar_t__> scale_gamma_flat__;
        current_statement__ = 81;
        scale_gamma_flat__ = context__.vals_r("scale_gamma");
        current_statement__ = 81;
        pos__ = 1;
        current_statement__ = 81;
        for (int sym1__ = 1; sym1__ <= m; ++sym1__) {
          current_statement__ = 81;
          stan::model::assign(scale_gamma, scale_gamma_flat__[(pos__ - 1)],
            "assigning variable scale_gamma", stan::model::index_uni(sym1__));
          current_statement__ = 81;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 81;
      stan::math::check_greater_or_equal(function__, "scale_gamma",
        scale_gamma, 0);
      current_statement__ = 82;
      stan::math::validate_non_negative_index("means", "p", p);
      current_statement__ = 83;
      context__.validate_dims("data initialization", "means", "double",
        std::vector<size_t>{static_cast<size_t>(p)});
      means_data__ = Eigen::Matrix<double,-1,1>::Constant(p,
                       std::numeric_limits<double>::quiet_NaN());
      new (&means)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(means_data__.data(), p);
      {
        std::vector<local_scalar_t__> means_flat__;
        current_statement__ = 83;
        means_flat__ = context__.vals_r("means");
        current_statement__ = 83;
        pos__ = 1;
        current_statement__ = 83;
        for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
          current_statement__ = 83;
          stan::model::assign(means, means_flat__[(pos__ - 1)],
            "assigning variable means", stan::model::index_uni(sym1__));
          current_statement__ = 83;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 84;
      stan::math::validate_non_negative_index("sdv", "p", p);
      current_statement__ = 85;
      context__.validate_dims("data initialization", "sdv", "double",
        std::vector<size_t>{static_cast<size_t>(p)});
      sdv_data__ = Eigen::Matrix<double,-1,1>::Constant(p,
                     std::numeric_limits<double>::quiet_NaN());
      new (&sdv) Eigen::Map<Eigen::Matrix<double,-1,1>>(sdv_data__.data(), p);
      {
        std::vector<local_scalar_t__> sdv_flat__;
        current_statement__ = 85;
        sdv_flat__ = context__.vals_r("sdv");
        current_statement__ = 85;
        pos__ = 1;
        current_statement__ = 85;
        for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
          current_statement__ = 85;
          stan::model::assign(sdv, sdv_flat__[(pos__ - 1)],
            "assigning variable sdv", stan::model::index_uni(sym1__));
          current_statement__ = 85;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 85;
      stan::math::check_greater_or_equal(function__, "sdv", sdv, 0);
      current_statement__ = 86;
      stan::math::validate_non_negative_index("log_time", "n", n);
      current_statement__ = 87;
      log_time_data__ = Eigen::Matrix<double,-1,1>::Constant(n,
                          std::numeric_limits<double>::quiet_NaN());
      new (&log_time)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(log_time_data__.data(), n);
      current_statement__ = 87;
      stan::model::assign(log_time, stan::math::log(time),
        "assigning variable log_time");
      current_statement__ = 88;
      stan::math::validate_non_negative_index("beta", "p", p);
      current_statement__ = 89;
      stan::math::validate_non_negative_index("gamma", "m", m);
      current_statement__ = 90;
      stan::math::validate_non_negative_index("eta", "n", n);
      current_statement__ = 91;
      stan::math::validate_non_negative_index("H", "n", n);
      current_statement__ = 92;
      stan::math::validate_non_negative_index("log_h", "n", n);
      current_statement__ = 93;
      stan::math::validate_non_negative_index("log_lik", "n", n);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = p + m;
  }
  inline std::string model_name() const final {
    return "model_spbp";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_spbp_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p, DUMMY_VAR__);
      current_statement__ = 1;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(p);
      Eigen::Matrix<local_scalar_t__,-1,1> gamma =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(m, DUMMY_VAR__);
      current_statement__ = 2;
      gamma = in__.template read_constrain_lb<
                Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, m);
      Eigen::Matrix<local_scalar_t__,-1,1> eta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(eta, stan::math::multiply(X, beta),
        "assigning variable eta");
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 4;
      alpha = 0.0;
      Eigen::Matrix<local_scalar_t__,-1,1> H =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> log_h =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
      current_statement__ = 34;
      if (stan::math::logical_eq(M, 2)) {
        current_statement__ = 12;
        stan::math::validate_non_negative_index("b", "n", n);
        current_statement__ = 13;
        stan::math::validate_non_negative_index("b", "m", m);
        Eigen::Matrix<local_scalar_t__,-1,-1> b =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(n, m, DUMMY_VAR__);
        current_statement__ = 15;
        stan::math::validate_non_negative_index("B", "n", n);
        current_statement__ = 16;
        stan::math::validate_non_negative_index("B", "m", m);
        Eigen::Matrix<local_scalar_t__,-1,-1> B =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(n, m, DUMMY_VAR__);
        current_statement__ = 18;
        stan::math::validate_non_negative_index("y", "n", n);
        Eigen::Matrix<local_scalar_t__,-1,1> y =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
        current_statement__ = 19;
        stan::model::assign(y, stan::math::subtract(log_time, eta),
          "assigning variable y");
        local_scalar_t__ tau_a = DUMMY_VAR__;
        current_statement__ = 20;
        tau_a = (stan::math::min(log_time) - stan::math::max(eta));
        local_scalar_t__ tau_b = DUMMY_VAR__;
        current_statement__ = 21;
        tau_b = (stan::math::max(log_time) - stan::math::min(eta));
        local_scalar_t__ range = DUMMY_VAR__;
        current_statement__ = 22;
        range = (tau_b - tau_a);
        current_statement__ = 23;
        stan::math::validate_non_negative_index("u", "n", n);
        Eigen::Matrix<local_scalar_t__,-1,1> u =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
        current_statement__ = 24;
        stan::model::assign(u,
          stan::math::fmin(
            stan::math::fmax(
              stan::math::divide(stan::math::subtract(y, tau_a),
                stan::math::fmax(range, 1e-12)), 1e-12), (1 - 1e-12)),
          "assigning variable u");
        current_statement__ = 28;
        for (int j = 1; j <= m; ++j) {
          current_statement__ = 25;
          stan::model::assign(b, stan::math::pow(u, (j - 1)),
            "assigning variable b", stan::model::index_omni(),
            stan::model::index_uni(j));
          current_statement__ = 26;
          stan::model::assign(B,
            stan::math::divide(stan::math::pow(u, j), j),
            "assigning variable B", stan::model::index_omni(),
            stan::model::index_uni(j));
        }
        current_statement__ = 29;
        stan::model::assign(b,
          stan::math::divide(
            stan::math::multiply(stan::model::deep_copy(b), P), range),
          "assigning variable b");
        current_statement__ = 30;
        stan::model::assign(B,
          stan::math::multiply(stan::model::deep_copy(B), P),
          "assigning variable B");
        current_statement__ = 31;
        stan::model::assign(H, cumhaz(B, gamma, eta, M, pstream__),
          "assigning variable H");
        current_statement__ = 32;
        stan::model::assign(log_h,
          log_haz(b, B, gamma, eta, log_time, M, pstream__),
          "assigning variable log_h");
      } else {
        current_statement__ = 8;
        alpha = stan::math::sum(
                  stan::math::elt_divide(
                    stan::math::elt_multiply(beta, means), sdv));
        current_statement__ = 9;
        stan::model::assign(H, cumhaz(G, gamma, eta, M, pstream__),
          "assigning variable H");
        current_statement__ = 10;
        stan::model::assign(log_h,
          log_haz(g, G, gamma, eta, log_time, M, pstream__),
          "assigning variable log_h");
      }
      Eigen::Matrix<local_scalar_t__,-1,1> log_lik =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
      current_statement__ = 7;
      stan::model::assign(log_lik,
        stan::math::add(stan::math::minus(H),
          stan::math::elt_multiply(status, log_h)),
        "assigning variable log_lik");
      {
        current_statement__ = 35;
        lp_accum__.add(stan::math::sum(log_lik));
        current_statement__ = 48;
        if (stan::math::logical_eq(approach, 1)) {
          current_statement__ = 40;
          for (int j = 1; j <= p; ++j) {
            current_statement__ = 38;
            if (stan::math::logical_eq(
                  stan::model::rvalue(priordist_beta, "priordist_beta",
                    stan::model::index_uni(j)), 0)) {
              current_statement__ = 37;
              lp_accum__.add((stan::math::normal_lpdf<false>(beta,
                                stan::model::rvalue(location_beta,
                                  "location_beta", stan::model::index_uni(j)),
                                stan::model::rvalue(scale_beta, "scale_beta",
                                  stan::model::index_uni(j))) +
                stan::math::log(
                  stan::model::rvalue(sdv, "sdv", stan::model::index_uni(j)))));
            } else {
              current_statement__ = 36;
              lp_accum__.add((stan::math::logistic_lpdf<false>(beta,
                                stan::model::rvalue(location_beta,
                                  "location_beta", stan::model::index_uni(j)),
                                stan::model::rvalue(scale_beta, "scale_beta",
                                  stan::model::index_uni(j))) +
                stan::math::log(
                  stan::model::rvalue(sdv, "sdv", stan::model::index_uni(j)))));
            }
          }
          current_statement__ = 46;
          for (int j = 1; j <= m; ++j) {
            current_statement__ = 44;
            if (stan::math::logical_eq(
                  stan::model::rvalue(priordist_gamma, "priordist_gamma",
                    stan::model::index_uni(j)), 0)) {
              current_statement__ = 43;
              lp_accum__.add(stan::math::lognormal_lpdf<propto__>(
                               stan::model::rvalue(gamma, "gamma",
                                 stan::model::index_uni(j)),
                               stan::model::rvalue(location_gamma,
                                 "location_gamma", stan::model::index_uni(j)),
                               stan::model::rvalue(scale_gamma,
                                 "scale_gamma", stan::model::index_uni(j))));
            } else {
              current_statement__ = 41;
              lp_accum__.add(stan::math::normal_lpdf<propto__>(
                               stan::model::rvalue(gamma, "gamma",
                                 stan::model::index_uni(j)),
                               stan::model::rvalue(location_gamma,
                                 "location_gamma", stan::model::index_uni(j)),
                               stan::model::rvalue(scale_gamma,
                                 "scale_gamma", stan::model::index_uni(j))));
            }
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_spbp_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> beta =
        Eigen::Matrix<double,-1,1>::Constant(p,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(p);
      Eigen::Matrix<double,-1,1> gamma =
        Eigen::Matrix<double,-1,1>::Constant(m,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      gamma = in__.template read_constrain_lb<
                Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, m);
      Eigen::Matrix<double,-1,1> eta =
        Eigen::Matrix<double,-1,1>::Constant(n,
          std::numeric_limits<double>::quiet_NaN());
      double alpha = std::numeric_limits<double>::quiet_NaN();
      Eigen::Matrix<double,-1,1> H =
        Eigen::Matrix<double,-1,1>::Constant(n,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> log_h =
        Eigen::Matrix<double,-1,1>::Constant(n,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> log_lik =
        Eigen::Matrix<double,-1,1>::Constant(n,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(beta);
      out__.write(gamma);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 3;
      stan::model::assign(eta, stan::math::multiply(X, beta),
        "assigning variable eta");
      current_statement__ = 4;
      alpha = 0.0;
      current_statement__ = 34;
      if (stan::math::logical_eq(M, 2)) {
        current_statement__ = 12;
        stan::math::validate_non_negative_index("b", "n", n);
        current_statement__ = 13;
        stan::math::validate_non_negative_index("b", "m", m);
        Eigen::Matrix<double,-1,-1> b =
          Eigen::Matrix<double,-1,-1>::Constant(n, m,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 15;
        stan::math::validate_non_negative_index("B", "n", n);
        current_statement__ = 16;
        stan::math::validate_non_negative_index("B", "m", m);
        Eigen::Matrix<double,-1,-1> B =
          Eigen::Matrix<double,-1,-1>::Constant(n, m,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 18;
        stan::math::validate_non_negative_index("y", "n", n);
        Eigen::Matrix<double,-1,1> y =
          Eigen::Matrix<double,-1,1>::Constant(n,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 19;
        stan::model::assign(y, stan::math::subtract(log_time, eta),
          "assigning variable y");
        double tau_a = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 20;
        tau_a = (stan::math::min(log_time) - stan::math::max(eta));
        double tau_b = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 21;
        tau_b = (stan::math::max(log_time) - stan::math::min(eta));
        double range = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 22;
        range = (tau_b - tau_a);
        current_statement__ = 23;
        stan::math::validate_non_negative_index("u", "n", n);
        Eigen::Matrix<double,-1,1> u =
          Eigen::Matrix<double,-1,1>::Constant(n,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 24;
        stan::model::assign(u,
          stan::math::fmin(
            stan::math::fmax(
              stan::math::divide(stan::math::subtract(y, tau_a),
                stan::math::fmax(range, 1e-12)), 1e-12), (1 - 1e-12)),
          "assigning variable u");
        current_statement__ = 28;
        for (int j = 1; j <= m; ++j) {
          current_statement__ = 25;
          stan::model::assign(b, stan::math::pow(u, (j - 1)),
            "assigning variable b", stan::model::index_omni(),
            stan::model::index_uni(j));
          current_statement__ = 26;
          stan::model::assign(B,
            stan::math::divide(stan::math::pow(u, j), j),
            "assigning variable B", stan::model::index_omni(),
            stan::model::index_uni(j));
        }
        current_statement__ = 29;
        stan::model::assign(b,
          stan::math::divide(
            stan::math::multiply(stan::model::deep_copy(b), P), range),
          "assigning variable b");
        current_statement__ = 30;
        stan::model::assign(B,
          stan::math::multiply(stan::model::deep_copy(B), P),
          "assigning variable B");
        current_statement__ = 31;
        stan::model::assign(H, cumhaz(B, gamma, eta, M, pstream__),
          "assigning variable H");
        current_statement__ = 32;
        stan::model::assign(log_h,
          log_haz(b, B, gamma, eta, log_time, M, pstream__),
          "assigning variable log_h");
      } else {
        current_statement__ = 8;
        alpha = stan::math::sum(
                  stan::math::elt_divide(
                    stan::math::elt_multiply(beta, means), sdv));
        current_statement__ = 9;
        stan::model::assign(H, cumhaz(G, gamma, eta, M, pstream__),
          "assigning variable H");
        current_statement__ = 10;
        stan::model::assign(log_h,
          log_haz(g, G, gamma, eta, log_time, M, pstream__),
          "assigning variable log_h");
      }
      current_statement__ = 7;
      stan::model::assign(log_lik,
        stan::math::add(stan::math::minus(H),
          stan::math::elt_multiply(status, log_h)),
        "assigning variable log_lik");
      if (emit_transformed_parameters__) {
        out__.write(eta);
        out__.write(alpha);
        out__.write(H);
        out__.write(log_h);
        out__.write(log_lik);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(beta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(p),
        "assigning variable beta");
      out__.write(beta);
      Eigen::Matrix<local_scalar_t__,-1,1> gamma =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(m, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(gamma,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(m),
        "assigning variable gamma");
      out__.write_free_lb(0, gamma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "beta", "double",
        std::vector<size_t>{static_cast<size_t>(p)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "gamma", "double",
        std::vector<size_t>{static_cast<size_t>(m)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 1;
        beta_flat__ = context__.vals_r("beta");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(beta, beta_flat__[(pos__ - 1)],
            "assigning variable beta", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta);
      Eigen::Matrix<local_scalar_t__,-1,1> gamma =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(m, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> gamma_flat__;
        current_statement__ = 2;
        gamma_flat__ = context__.vals_r("gamma");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= m; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(gamma, gamma_flat__[(pos__ - 1)],
            "assigning variable gamma", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, gamma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"beta", "gamma"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"eta", "alpha", "H", "log_h", "log_lik"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(p)},
                std::vector<size_t>{static_cast<size_t>(m)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(n)},
             std::vector<size_t>{},
             std::vector<size_t>{static_cast<size_t>(n)},
             std::vector<size_t>{static_cast<size_t>(n)},
             std::vector<size_t>{static_cast<size_t>(n)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= m; ++sym1__) {
      param_names__.emplace_back(std::string() + "gamma" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        param_names__.emplace_back(std::string() + "eta" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "alpha");
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        param_names__.emplace_back(std::string() + "H" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_h" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= m; ++sym1__) {
      param_names__.emplace_back(std::string() + "gamma" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        param_names__.emplace_back(std::string() + "eta" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "alpha");
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        param_names__.emplace_back(std::string() + "H" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_h" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(p) + "},\"block\":\"parameters\"},{\"name\":\"gamma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(m) + "},\"block\":\"parameters\"},{\"name\":\"eta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n) + "},\"block\":\"transformed_parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"H\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_h\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n) + "},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(p) + "},\"block\":\"parameters\"},{\"name\":\"gamma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(m) + "},\"block\":\"parameters\"},{\"name\":\"eta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n) + "},\"block\":\"transformed_parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"H\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_h\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n) + "},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (p + m);
    const size_t num_transformed = emit_transformed_parameters * (((((n + 1)
      + n) + n) + n));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (p + m);
    const size_t num_transformed = emit_transformed_parameters * (((((n + 1)
      + n) + n) + n));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_spbp_namespace::model_spbp;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_spbp_namespace::profiles__;
}
#endif
#endif
